name: Pytest
description: Runs a pytest in the given dir
inputs:
  working_dir:
    description: 'Directory where tests live'
    required: true
  python_version_matrix:
    description: 'Lst of python versions'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python_version_matrix }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version_matrix }}
    - name: Install testing dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install black pytest

        pwd

        python -m venv venv
        source venv/bin/activate

        if [[ -f requirements.txt ]]; then
          pip install -r requirements.txt
        fi

        if [[ -f test-requirements.txt ]]; then
          pip install -r test-requirements.txt
        fi
        pip list

        deactivate
    - name: Lint with Black
      shell: bash
      run: |
        black . --check
    - name: Test with pytest
      shell: bash
      run: |
        pwd 

        source venv/bin/activate
        pip list
        pwd
        cd ${{ inputs.working_dir }}
        pytest .

        deactivate