name: Main Branch Workflow

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
permissions:
  id-token: write
  contents: read

jobs:
  prerequisites:
    name: "Prerequisites"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency: ${{ inputs.env_name }}
    outputs:
      lambdas_changed: ${{ steps.prerequisites.outputs.lambdas_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Prerequisites
        id: prerequisites
        uses: IAG-Ent/.github/.github/actions/prerequisites@main
  lambda_tests_and_package:
    name: "Run Lambda Tests and Package"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency: ${{ inputs.env_name }}
    needs: prerequisites
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Lambda Tests and Package
        uses: IAG-Ent/.github/.github/actions/lambda_tests_and_package@main
        with:
          lambda_names: "${{ needs.prerequisites.outputs.lambdas_changed  }}"
          python_version_matrix: "${{ matrix.python-version  }}"
          aws_role: ${{ vars.AWS_OIDC_ROLE }}
          lambda_code_bucket: "ccoe-ecp-${{ vars.ACCOUNT_ID }}-eu-west-1-lambda-code"
    
  terraform_plan:
    name: "Terraform Plan dev-ecptest"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency: ${{ inputs.env_name }}
    needs: 
      - prerequisites
      - lambda_tests_and_package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Terraform
        uses: IAG-Ent/.github/.github/actions/terraform_run@main
        with:
          aws_role: ${{ vars.AWS_OIDC_ROLE }}
          terraform_action: 'plan'
          terraform_version: 1.5.6
          tfstate_bucket: ccoe-ecp-${{ vars.ACCOUNT_ID }}-eu-west-1-tfstate
          tfstate_dynamodb_table: ccoe-ecp-${{ vars.ACCOUNT_ID }}-eu-west-1-tfstate
          tf_working_dir: terraform
  
  terraform_apply:
    name: "Terraform Apply dev-ecptest"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency: ${{ inputs.env_name }}
    needs: 
      - prerequisites
      - terraform_plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Terraform
        uses: IAG-Ent/.github/.github/actions/terraform_run@main
        with:
          aws_role: ${{ vars.AWS_OIDC_ROLE }}
          terraform_action: 'apply'
          terraform_version: 1.5.6
          tfstate_bucket: ccoe-ecp-${{ vars.ACCOUNT_ID }}-eu-west-1-tfstate
          tfstate_dynamodb_table: ccoe-ecp-${{ vars.ACCOUNT_ID }}-eu-west-1-tfstate
          tf_working_dir: terraform