name: PR Workflow

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      protected_env_name:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  prerequisites:
    name: "Prerequisites"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency: ${{ inputs.env_name }}
    outputs:
      lambdas_changed: ${{ steps.prerequisites.outputs.lambdas_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Prerequisites
        id: prerequisites
        uses: ./.github/workflows/prerequisites
  lambda_tests_and_package:
    name: "Run Lambda Tests and Package"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency: ${{ inputs.env_name }}
    needs: prerequisites
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Lambda Tests and Package
        uses: ./.github/workflows/lambda_tests_and_package
        with:
          lambda_names: "${{ needs.prerequisites.outputs.lambdas_changed  }}"
          python_version_matrix: "${{ matrix.python-version  }}"
          aws_role: ${{ vars.AWS_OIDC_ROLE }}
          lambda_code_bucket: "ccoe-ecp-${{ vars.DEV_ECPTEST_ACCOUNT_ID }}-eu-west-1-lambda-code"
    
  terraform_plan:
    name: "Terraform Plan dev-ecptest"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency: ${{ inputs.env_name }}
    needs: 
      - prerequisites
      - lambda_tests_and_package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Terraform
        uses: ./.github/workflows/terraform_run
        with:
          aws_role: ${{ vars.AWS_OIDC_ROLE }}
          terraform_action: 'plan'
          terraform_version: 1.5.6
          tfstate_bucket: ccoe-ecp-${{ vars.DEV_ECPTEST_ACCOUNT_ID }}-eu-west-1-tfstate
          tfstate_dynamodb_table: ccoe-ecp-${{ vars.DEV_ECPTEST_ACCOUNT_ID }}-eu-west-1-tfstate
          tf_working_dir: terraform
  
  terraform_apply:
    name: "Terraform Apply dev-ecptest"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency: ${{ inputs.env_name }}
    needs: 
      - prerequisites
      - terraform_plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Terraform
        uses: ./.github/workflows/terraform_run
        with:
          aws_role: ${{ vars.AWS_OIDC_ROLE }}
          terraform_action: 'apply'
          terraform_version: 1.5.6
          tfstate_bucket: ccoe-ecp-${{ vars.ACCOUNT_ID }}-eu-west-1-tfstate
          tfstate_dynamodb_table: ccoe-ecp-${{ vars.ACCOUNT_ID }}-eu-west-1-tfstate
          tf_working_dir: terraform
  
  wait_revert_command:
    name: "Manual testing"
    timeout-minutes: 180 #3 hours
    runs-on: ubuntu-latest
    environment: ${{ inputs.protected_env_name }}
    needs:
      - terraform_apply
    steps:
      - name: Revert Dev Approved
        run: |
          echo "Manual testing completed. Proceed to revert changes in Dev environment"

  terraform_apply_main:
    name: "Terraform Apply from origin/main"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    concurrency: ${{ inputs.env_name }}
    if: ${{ always() }}
    needs: 
      - prerequisites
      - wait_revert_command
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Run Terraform
        uses: ./.github/workflows/terraform_run
        with:
          aws_role: ${{ vars.AWS_OIDC_ROLE }}
          terraform_action: 'apply'
          terraform_version: 1.5.6
          tfstate_bucket: ccoe-ecp-${{ vars.ACCOUNT_ID }}-eu-west-1-tfstate
          tfstate_dynamodb_table: ccoe-ecp-${{ vars.ACCOUNT_ID }}-eu-west-1-tfstate
          tf_working_dir: terraform